package com.company.module.sales.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Configuration;

import javax.annotation.PostConstruct;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

/**
 * SAP JCo Destination 설정.
 * sap-connection.yml의 값을 기반으로 JCo destination 파일을 생성합니다.
 *
 * <p>SAP JCo는 {@code <destination_name>.jcoDestination} 파일을 읽어
 * 연결 정보를 구성합니다. 이 클래스는 애플리케이션 시작 시
 * SapProperties 값으로 해당 파일을 자동 생성합니다.</p>
 */
@Slf4j
@Configuration
@RequiredArgsConstructor
public class SapJCoConfig {

    /** JCo Destination 이름 — RFC 호출 시 이 이름으로 참조 */
    public static final String DESTINATION_NAME = "SAP_SNOP";

    private final SapProperties sapProperties;

    /**
     * 앱 시작 시 JCo Destination 프로퍼티 파일을 생성합니다.
     * 파일 위치: 현재 작업 디렉토리 / SAP_SNOP.jcoDestination
     */
    @PostConstruct
    public void createDestinationFile() {
        if (isBlank(sapProperties.getHost())) {
            log.warn("SAP Host가 설정되지 않았습니다. JCo Destination 파일을 생성하지 않습니다.");
            return;
        }

        Properties props = new Properties();
        props.setProperty("jco.client.ashost", sapProperties.getHost());
        props.setProperty("jco.client.sysnr", sapProperties.getSystemNumber());
        props.setProperty("jco.client.client", sapProperties.getClient());
        props.setProperty("jco.client.user", sapProperties.getUser());
        props.setProperty("jco.client.lang", sapProperties.getLanguage());

        // 비밀번호는 설정된 경우에만 포함
        if (!isBlank(sapProperties.getPassword())) {
            props.setProperty("jco.client.passwd", sapProperties.getPassword());
        }

        // 연결 풀 설정
        props.setProperty("jco.destination.pool_capacity",
                String.valueOf(sapProperties.getPoolCapacity()));
        props.setProperty("jco.destination.peak_limit",
                String.valueOf(sapProperties.getPeakLimit()));

        File destFile = new File(DESTINATION_NAME + ".jcoDestination");
        try (FileOutputStream fos = new FileOutputStream(destFile)) {
            props.store(fos, "SAP JCo Destination — auto-generated by SapJCoConfig");
            log.info("SAP JCo Destination 파일 생성 완료: {} (host={}, user={})",
                    destFile.getAbsolutePath(), sapProperties.getHost(), sapProperties.getUser());
        } catch (IOException e) {
            log.error("SAP JCo Destination 파일 생성 실패: {}", e.getMessage(), e);
        }
    }

    private boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }
}
